name: APIM Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name, for example cn-int'
        required: true
        type: choice
        options:
          - cn-int
          - cn-pre
          - cn-prod
        default: 'cn-int'


jobs:
  terraform:
    name: Terraform APIM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: APIM/src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.8

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: |
          tfvars_file="../env/${{ github.event.inputs.environment }}.tfvars"
          echo "Using tfvars file: $tfvars_file"
          terraform plan -var-file="$tfvars_file" -out=plan.tfplan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: terraform apply -auto-approve plan.tfplan
